### ISSUE TITLE
seeking suggestion for processing other cwes

### ISSUE THREAD

**Issue by flynightair** [ymirsky/VulChecker#1]
hi, thanks for sharing the wonderful work. If i want to train on other cwes except for 121,190,415,416, what should i do? Following the processing steps as mentioned or if i need to modify the hector tool? Looking forward for your reply, many thanks.

**Comment by ymirsky** [comment]
Hi,
If you want to extend the pipeline to other CWEs, you will need to extend the hector tool. 
Primarily, you will need to decide what types of instructions should be marked as potential manifestation points. Perhaps @michaelbrownuc can elaborate further.

**Comment by flynightair** [comment]
ok, thanks for your reply.

**Comment by michaelbrownuc** [comment]
yes, to identify new CWEs you will need to copy one of the LLVM pipelines and adapt it to label your training data, as well as process novel samples. see the llap tool for an example, and I can answer questions you have.

**Comment by flynightair** [comment]
> yes, to identify new CWEs you will need to copy one of the LLVM pipelines and adapt it to label your training data, as well as process novel samples. see the llap tool for an example, and I can answer questions you have.

thanks
