### ISSUE TITLE
the difference in multi TARGETs

### ISSUE THREAD

**Issue by flynightair** [ymirsky/VulChecker#4]
Hi, ymirsky. If there are multi numbers of TARGET, how does the choice of TARGET affect the final result?

**Comment by ymirsky** [comment]
Different binaries (eg executables) can be compiled from the same source
code. For example unit tests, portable libraries or the program itself.
Therefore, it matters a lot. If your goal is to analyze the main program,
then you must course the target for the main program.

**Comment by flynightair** [comment]
> Different binaries (eg executables) can be compiled from the same source code. For example unit tests, portable libraries or the program itself. Therefore, it matters a lot. If your goal is to analyze the main program, then you must course the target for the main program.
>

OK， thanks
